SECRET_KEY = "To define"

DB_NAME = "cookiecutter"

DB_USER_DEV = "postgres"
DB_PASSWORD_DEV = "test"

DB_USER_PREPROD = ""
DB_PASSWORD_PREPROD = ""

DB_USER_TEST = ""
DB_PASSWORD_TEST = ""

DB_USER_PROD = ""
DB_PASSWORD_PROD = ""

STATIC_ROOT = ""

DEFAULT_FROM_EMAIL = ""
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
