# dependabot.yml file

version: 2
updates:
  # Keep poetry dependencies up to date
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "poetry dependencies"
    target-branch: "main"
    assignees:
      - "{{cookiecutter.git_username}}"
    commit-message:
      # Prefix all commit messages with "poetry"
      prefix: "poetry"